name: l1deepmet
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - tensorflow
  - keras
  - hls4ml>=1.0           # 0.6 didn't support Embedding or Keras 3 models
  - pyyaml
  - pip
  - mplhep
  - scipy
  - pytest
  - uproot
  - awkward
  - seaborn               # used by synthesis/validate.py pairplots
  - pandas
  - pip:
      - qkeras
      - HGQ2
      - da4ml>=0.5.2,<0.6 # required by hls4ml>=1.3 to avoid v2-handler fallback warnings
      - dvc[s3]