# DVC Parameters File
# This file defines all parameters for the L1DeepMET pipeline

preprocess:
  # Input data configuration
  data_root: "/home/users/dprimosc/L1DeepMET/data/25Jul8_140X_v0"
    
  output_tag: "25Jul8_140X_v0"
  output_dir: "data/preprocessed"
  plot_dir: "outputs/preprocessing_plots"

  # Sample configuration with desired event counts
  samples:
    TT_PU200: 100000
    VBFHToInvisible_PU200: 48000
  
  # ROOT file variables to load
  var_list:
    - nL1PuppiCands
    - L1PuppiCands_pt
    - L1PuppiCands_eta
    - L1PuppiCands_phi
    - L1PuppiCands_charge
    - L1PuppiCands_pdgId
    - L1PuppiCands_puppiWeight
    - L1PuppiCands_dxyErr
    - HGCal3DCl_firstHcal1layers
    - HGCal3DCl_firstHcal3layers
    - HGCal3DCl_firstHcal5layers
    - HGCal3DCl_hoe
    - HGCal3DCl_showerlength
    - HGCal3DCl_coreshowerlength
  
  # MC truth variables
  var_list_mc:
    - genMet_pt
    - genMet_phi
  
  # Discrete variable encoding
  discrete_encoding:
    L1PuppiCands_charge:
      -999.0: 0
      -1.0: 1
      0.0: 2
      1.0: 3
    L1PuppiCands_pdgId:
      -999.0: 0
      -211.0: 1
      -130.0: 2
      -22.0: 3
      -13.0: 4
      -11.0: 5
      11.0: 5
      13.0: 4
      22.0: 3
      130.0: 2
      211.0: 1
  
  # Processing parameters
  max_pf_candidates: 128
  outlier_threshold: 500.0  # GeV
  random_seed: 42
  
  train_val_test_split:
    train: 0.8
    val: 0.1
    test: 0.1


# Training parameters
train:
  batch_size: 1024
  epochs: 100
  mode: 1  # 0: direct regression, 1: per-particle weight, 2: global weight

# Model parameters
model:
  type: dense  # Model architecture type
  units: [64, 32, 16]  # Hidden layer units
  activation: tanh  # Activation function
  with_bias: false  # Add bias to per-particle predictions

# Loss function parameters
loss:
  mae_weight: 1.0
  mse_weight: 1.0
  binned_weight: 200.0

# Optimizer parameters
optimizer:
  type: adam
  learning_rate: 0.001

# Callback parameters
callbacks:
  early_stopping:
    monitor: val_loss
    patience: 40
  reduce_lr:
    monitor: val_loss
    factor: 0.5
    patience: 10
    min_delta: 0.0001
    min_lr: 0.000001

# Data parameters
data:
  maxNPF: 128  # Maximum number of PF candidates