#!/usr/bin/env bash
# Apply (or revert) the L1DeepMET FastPUPPI patches on the external/FastPUPPI
# submodule. Two patches: one for stage 1 (runInputs131X.py — re-emulates L1
# from MINIAOD) and one for stage 2 (runPerformanceNTuple.py — analyzes and
# writes the perfNano FlatTables).
#
# Usage:
#   scripts/apply_ntuple_recipe.sh apply         # apply both patches
#   scripts/apply_ntuple_recipe.sh revert        # revert both
#   scripts/apply_ntuple_recipe.sh check         # report applied state
#
# The patches live under patches/ and are generated by `git diff` against
# the FastPUPPI 14_0_X branch (the one used for the 25Jul8 production).
# Phase2Spring23 MINIAOD inputs feed runInputs131X.py → inputs131X.root →
# runPerformanceNTuple.py → perfNano.root.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE="${REPO_ROOT}/external/FastPUPPI"

# Ordered list of patches; each patches one file in the submodule.
# Stage 1 is runInputs140X.py (FastPUPPI 14_2_X branch — D110 + 141X GT,
# matches Phase2Spring24 inputs and the user's 25Jul8 production provenance).
PATCHES=(
    "${REPO_ROOT}/patches/runInputs140X.patch"
    "${REPO_ROOT}/patches/runPerformanceNTuple.patch"
)

if [[ ! -d "$SUBMODULE" ]]; then
    echo "FATAL: submodule not initialised. Run: git submodule update --init external/FastPUPPI" >&2
    exit 2
fi
for P in "${PATCHES[@]}"; do
    if [[ ! -f "$P" ]]; then
        echo "FATAL: patch not found at $P" >&2
        exit 2
    fi
done

cmd="${1:-check}"

# Helper: is patch $1 already applied to the submodule?
_applied() {
    cd "$SUBMODULE"
    patch --dry-run -p1 -R -i "$1" >/dev/null 2>&1
}

case "$cmd" in
    apply)
        cd "$SUBMODULE"
        for P in "${PATCHES[@]}"; do
            if _applied "$P"; then
                echo "ℹ $(basename "$P") already applied"
                continue
            fi
            patch -p1 -i "$P"
            echo "✓ $(basename "$P") applied"
        done
        ;;
    revert)
        cd "$SUBMODULE"
        # Revert in reverse order so later patches don't depend on earlier ones still being there.
        for ((i=${#PATCHES[@]}-1; i>=0; i--)); do
            P="${PATCHES[$i]}"
            if _applied "$P"; then
                patch -p1 -R -i "$P"
                echo "✓ $(basename "$P") reverted"
            else
                echo "ℹ $(basename "$P") not currently applied"
            fi
        done
        ;;
    check)
        all_applied=true
        any_applied=false
        for P in "${PATCHES[@]}"; do
            if _applied "$P"; then
                any_applied=true
            else
                all_applied=false
            fi
        done
        if $all_applied; then
            echo "applied"
        elif $any_applied; then
            echo "partial"
        else
            echo "not-applied"
        fi
        ;;
    *)
        echo "Usage: $0 {apply|revert|check}" >&2
        exit 1
        ;;
esac
