#!/usr/bin/env bash
# Apply (or revert) the L1DeepMET runPerformanceNTuple.py patch on the
# external/FastPUPPI submodule.
#
# Usage:
#   scripts/apply_ntuple_recipe.sh apply         # apply the patch
#   scripts/apply_ntuple_recipe.sh revert        # revert to upstream
#   scripts/apply_ntuple_recipe.sh check         # report whether applied
#
# The patch lives at patches/runPerformanceNTuple.patch and is generated by
# diffing our extended saveCands() + opt-in helpers against upstream
# da727a3 (15_1_X tip).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE="${REPO_ROOT}/external/FastPUPPI"
PATCH="${REPO_ROOT}/patches/runPerformanceNTuple.patch"
TARGET="${SUBMODULE}/NtupleProducer/python/runPerformanceNTuple.py"

if [[ ! -d "$SUBMODULE" ]]; then
    echo "FATAL: submodule not initialised. Run: git submodule update --init external/FastPUPPI" >&2
    exit 2
fi
if [[ ! -f "$PATCH" ]]; then
    echo "FATAL: patch not found at $PATCH" >&2
    exit 2
fi

cmd="${1:-check}"

case "$cmd" in
    apply)
        cd "$SUBMODULE"
        # If already applied (subsequent run), skip silently
        if patch --dry-run -p1 -R -i "$PATCH" >/dev/null 2>&1; then
            echo "ℹ patch already applied"
            exit 0
        fi
        patch -p1 -i "$PATCH"
        echo "✓ patch applied"
        ;;
    revert)
        cd "$SUBMODULE"
        if patch --dry-run -p1 -R -i "$PATCH" >/dev/null 2>&1; then
            patch -p1 -R -i "$PATCH"
            echo "✓ patch reverted"
        else
            echo "ℹ nothing to revert (patch not currently applied)"
        fi
        ;;
    check)
        cd "$SUBMODULE"
        if patch --dry-run -p1 -R -i "$PATCH" >/dev/null 2>&1; then
            echo "applied"
        else
            echo "not-applied"
        fi
        ;;
    *)
        echo "Usage: $0 {apply|revert|check}" >&2
        exit 1
        ;;
esac
